mcc: "208" # Mobile Country Code value
mnc: "93" # Mobile Network Code value (2 or 3 digits)

nci: "0x000000010" # NR Cell Identity (36-bit)
idLength: 32 # NR gNB ID length in bits [22...32]
tac: 1 # Tracking Area Code

# Cell configuration
cellCfg:
  cellBarred: false
  reservedForOperatorUse: false

linkIp: 10.100.200.6
ngapIp: 10.100.200.6
gtpIp: 10.100.200.6

# List of AMF address information
amfConfigs:
  - address: free5gc-amf
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 0x1
    sd: 0x010203
  - sst: 0x1
    sd: 0x112233

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
